FROM alpine:edge

LABEL "MAINTAINER"="icaoberg"
LABEL "EMAIL"="icaoberg@psc.edu"
LABEL "SUPPORT"="help@psc.edu"
LABEL "REPOSITORY"="http://github.com/pscedu/singularity-jq"
LABEL "COPYRIGHT"="Copyright © 2021-2023-2022 Pittsburgh Supercomputing Center. All Rights Reserved."
LABEL "VERSION"="1.7.1-r0"

RUN apk update && apk add jq=1.7.1-r0-r1
